import { useState, useRef, useCallback, useEffect } from 'react'
import { getItem, removeItem } from '../utils/storage'
import { API_URL, parseJSONResponse } from '../api/client'

/**
 * Manages sidebar panel state, dictionary search, and knowledge point selection.
 *
 * @param {string} language - Current language code
 * @param {Array} knowledgePoints - Current knowledge points list
 * @param {Function} addPoint - Function to add a knowledge point
 * @param {Function} getPointById - Function to get a point by ID
 * @param {Object} conversationContextRef - Ref to current conversation context
 * @param {Function} getDictSystemPrompt - Returns the dictionary system prompt for the language
 * @returns {Object} Sidebar state + handlers
 */
export function useSidebarState(language, knowledgePoints, addPoint, getPointById, conversationContextRef, getDictSystemPrompt) {
  const [sidebarContent, setSidebarContent] = useState(null)
  const [sidebarContentType, setSidebarContentType] = useState(null)
  const [expandedChinese, setExpandedChinese] = useState(false)
  const [dictQuery, setDictQuery] = useState('')
  const [dictLoading, setDictLoading] = useState(false)
  const [selectedPointId, setSelectedPointId] = useState(null)
  const [highlightedMessageId, setHighlightedMessageId] = useState(null)
  const [selectionBubble, setSelectionBubble] = useState(null)
  const selectionTimerRef = useRef(null)

  const dictSearchRef = useRef(null)

  // ── Shared dict search logic ─────────────────────────────────────
  const performDictSearch = useCallback(async (word) => {
    const apiKey = await getItem('deepseek_api_key')
    if (!apiKey) {
      setSidebarContent({ error: '⚠️ Please provide a valid API Key first.' })
      setSidebarContentType('dict')
      return null
    }

    const response = await fetch(API_URL, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${apiKey}` },
      body: JSON.stringify({
        model: 'deepseek-chat',
        messages: [
          { role: 'system', content: getDictSystemPrompt(language) },
          { role: 'user', content: `Define the word: "${word}"` },
        ],
        stream: false,
        temperature: 0,
      }),
    })

    if (!response.ok) {
      if (response.status === 401) {
        await removeItem('deepseek_api_key')
        setSidebarContent({ error: '⚠️ API Key is invalid or expired.' })
      } else {
        setSidebarContent({ error: `❌ Query failed (${response.status}).` })
      }
      return null
    }

    const data = await response.json()
    const aiResponse = data.choices[0].message.content

    try {
      return parseJSONResponse(aiResponse)
    } catch {
      setSidebarContent({ error: 'Failed to parse word definition', raw: aiResponse })
      return null
    }
  }, [language, getDictSystemPrompt])

  // ── Build knowledge point from dict result ───────────────────────
  const buildKnowledgePoint = useCallback((word, dictData) => ({
    // id is regenerated by addPoint; Date.now() here is a placeholder only
    id: Date.now(),
    word: dictData.word || word,
    type: dictData.type || 'word',
    meaning: dictData.definition || 'Definition not found',
    meaningChinese: dictData.meaningChinese || '',
    phonetic: dictData.phonetic || '',
    partOfSpeech: dictData.partOfSpeech || '',
    context: conversationContextRef.current?.scenario || 'Dictionary',
    examples: dictData.examples || [`Example using "${word}"`],
    createdAt: new Date().toISOString(),
    confirmed: false,
    status: 'active',
  }), [conversationContextRef])

  // ── Handlers ─────────────────────────────────────────────────────
  const handleDictSearch = useCallback(async () => {
    const word = dictQuery.trim()
    if (!word || dictLoading) return

    // 1. 先查重 — 如果已存在，直接显示，跳过 API
    const existing = knowledgePoints.find(
      (p) => p.word.toLowerCase() === word.toLowerCase() && p.status !== 'deleted'
    )
    if (existing) {
      setDictQuery(word)
      setSelectedPointId(existing.id)
      setSidebarContent(existing)
      setSidebarContentType('point')
      setExpandedChinese(false)
      setDictLoading(false)
      return
    }

    // 2. 不存在 → 调 API 生成
    setDictLoading(true)
    setSidebarContent(`🔍 Searching for "${word}"...`)
    setSidebarContentType('dict')

    try {
      const dictData = await performDictSearch(word)
      if (dictData) {
        const added = addPoint(buildKnowledgePoint(word, dictData))
        if (added) {
          setSelectedPointId(added.id)
          setSidebarContent(added)
          setSidebarContentType('point')
          setExpandedChinese(false)
        }
      }
    } catch {
      setSidebarContent({ error: '❌ Network error. Please try again.' })
      setSidebarContentType('dict')
    }
    setDictLoading(false)
  }, [dictQuery, dictLoading, knowledgePoints, performDictSearch, buildKnowledgePoint, addPoint])

  const handleDictSearchFromSelection = useCallback(async (word) => {
    // 1. 先查重 — 如果已存在，直接显示，跳过 API
    const existing = knowledgePoints.find(
      (p) => p.word.toLowerCase() === word.toLowerCase() && p.status !== 'deleted'
    )
    if (existing) {
      setDictQuery(word)
      setSelectedPointId(existing.id)
      setSidebarContent(existing)
      setSidebarContentType('point')
      setExpandedChinese(false)
      setDictLoading(false)
      return
    }

    // 2. 不存在 → 调 API 生成
    setDictQuery(word)
    setDictLoading(true)
    setSidebarContent(`🔍 Searching for "${word}"...`)
    setSidebarContentType('dict')

    try {
      const dictData = await performDictSearch(word)
      if (dictData) {
        const added = addPoint(buildKnowledgePoint(word, dictData))
        if (added) {
          setSelectedPointId(added.id)
          setSidebarContent(added)
          setSidebarContentType('point')
          setExpandedChinese(false)
        }
      }
    } catch {
      setSidebarContent({ error: '❌ Network error. Please try again.' })
      setSidebarContentType('dict')
    }
    setDictLoading(false)
  }, [knowledgePoints, performDictSearch, buildKnowledgePoint, addPoint])

  const handleDictKeyDown = useCallback((e) => {
    if (e.key === 'Enter') { e.preventDefault(); handleDictSearch() }
  }, [handleDictSearch])

  const handleSidebarUpdate = useCallback((content) => {
    setSidebarContent(content)
    setSidebarContentType('dict')
  }, [])

  const handleSidebarClose = useCallback(() => {
    setSidebarContent(null)
    setSidebarContentType(null)
    setExpandedChinese(false)
    setSelectedPointId(null)
  }, [])

  const handleSelectPoint = useCallback((pointId) => {
    setSelectedPointId(pointId)
    const point = getPointById(pointId)
    if (!point) return
    setSidebarContent(point)
    setSidebarContentType('point')
    setExpandedChinese(false)

    if (point.sourceMessageId) {
      setHighlightedMessageId(point.sourceMessageId)
      setTimeout(() => {
        const el = document.querySelector(`[data-message-id="${point.sourceMessageId}"]`)
        if (el) {
          el.scrollIntoView({ behavior: 'smooth', block: 'center' })
          el.classList.add('message-highlight')
          setTimeout(() => el.classList.remove('message-highlight'), 2000)
        }
      }, 100)
    }
  }, [getPointById])

  // ── Global keyboard shortcut ─────────────────────────────────────
  useEffect(() => {
    dictSearchRef.current = handleDictSearchFromSelection
  }, [handleDictSearchFromSelection])

  useEffect(() => {
    const handleKeyDown = (e) => {
      if (e.target.closest('input, textarea, [contenteditable]')) return
      if ((e.metaKey || e.ctrlKey) && e.shiftKey && (e.key === 'k' || e.key === 'K')) {
        e.preventDefault()
        const selection = window.getSelection().toString().trim()
        if (selection && dictSearchRef.current) dictSearchRef.current(selection)
      }
    }
    document.addEventListener('keydown', handleKeyDown)
    return () => document.removeEventListener('keydown', handleKeyDown)
  }, [])

  // ── Mobile selection bubble ──────────────────────────────────────
  const dismissSelectionBubble = useCallback(() => setSelectionBubble(null), [])

  useEffect(() => {
    const handleSelection = () => {
      if (selectionTimerRef.current) clearTimeout(selectionTimerRef.current)
      selectionTimerRef.current = setTimeout(() => {
        const sel = window.getSelection()
        if (!sel || sel.isCollapsed || !sel.toString().trim()) {
          setSelectionBubble(null)
          return
        }
        const text = sel.toString().trim()
        // Ignore selections inside inputs
        const node = sel.anchorNode
        if (node && node.parentElement?.closest('input, textarea')) {
          setSelectionBubble(null)
          return
        }
        const range = sel.getRangeAt(0).cloneRange()
        range.collapse(false)
        const rect = range.getClientRects().item(0)
        if (!rect) { setSelectionBubble(null); return }
        setSelectionBubble({
          word: text,
          x: rect.left + rect.width / 2,
          y: rect.top - 8,
        })
      }, 200)
    }
    document.addEventListener('selectionchange', handleSelection)
    return () => {
      document.removeEventListener('selectionchange', handleSelection)
      if (selectionTimerRef.current) clearTimeout(selectionTimerRef.current)
    }
  }, [])

  return {
    sidebarContent, sidebarContentType,
    expandedChinese, setExpandedChinese,
    dictQuery, setDictQuery,
    dictLoading,
    selectedPointId, setSelectedPointId,
    highlightedMessageId,
    selectionBubble, dismissSelectionBubble,
    handleSidebarUpdate, handleSidebarClose,
    handleSelectPoint,
    handleDictSearch, handleDictSearchFromSelection, handleDictKeyDown,
  }
}
